### ISSUE TITLE
Error when using node-fetch decorator without options object

### ISSUE THREAD

**Issue by ewoerner** [valeriangalliat/fetch-cookie#10]
```javascript
var fetch = require('fetch-cookie/node-fetch')(require('node-fetch'));
fetch('http://google.de', {}).catch(console.error); // works
fetch('http://google.de').catch(console.error); // doesn't work
```
The latter version throws an error:
```
TypeError: Cannot read property 'method' of undefined
    at …/node_modules/fetch-cookie/node-fetch.js:8:100
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by valeriangalliat** [comment]
Thanks for reporting, fixed as of 0.4.1. :)
